Q. 퀵 정렬(Quick sort)도 합병 정렬처럼 문제를 더 작은 문제를 쪼개서 해결하는 분할 정복(Divide and Conquer) 알고리즘이다.

- 이름처럼 속도가 빠르다. 시간 복잡도가 $O(n \log n)$인 다른 정렬 알고리즘과 비교해도 빠르다.
- 합병 정렬과 달리 추가 메모리 공간이 필요 없다.
- 불안정 정렬이다.
- 정렬된 배열일 때는 수행 시간이 늘어난다.

정렬 과정은 아래처럼 3단계로 구성된다.

- 분할(Divide): 정렬할 배열에서 기준 값(pivot)을 선택한다. 오름차순 정렬이면 피벗보다 작은 값은 피벗에 왼쪽에 배치하고 나머지를 피봇에 오른쪽에 배치하여 두 개의 부분 배열로 분할한다.
- 정복(Conquer): 부분 배열을 정렬한다. 보통 부분 배열의 길이가 1이 될 때까지 재귀 호출을 통해 분할한다.
- 결합(Merge): 정렬한 부분 배열을 하나로 합친다. 퀵 정렬을 제자리 정렬로 구현하면 사실상 결합 단계는 필요없다.([출처](https://wikidocs.net/219271))

다음 코드의 빈칸을 채워 병합정렬을 완성하세요.
```
def 합병정렬(입력리스트):
    입력리스트길이 = len(입력리스트)
    if 입력리스트길이 <= 1:
        return 입력리스트

    중간값 = 입력리스트길이 // 2
    그룹_하나 = 병합정렬(입력리스트[:중간값])
    그룹_둘 = 병합정렬(입력리스트[중간값:])
    결과값 = []

    while ([빈칸을 채워주세요]) and ([빈칸을 채워주세요]):
        if ([빈칸을 채워주세요]):
            결과값.append(그룹_하나.pop(0))
        elif ([빈칸을 채워주세요]):
            결과값.append(그룹_둘.pop(0))
    
    while 그룹_하나:
        결과값.append(그룹_하나.pop(0))
    while 그룹_둘:
        결과값.append(그룹_둘.pop(0))
    return 결과값

주어진리스트 = [180, 145, 165, 45, 170, 175, 173, 171]

print(합병정렬(주어진리스트))
```

In [8]:
# 풀이1: 주어진 리스트에 중복된 값이 존재하는 경우, 중복된 값을 모두 출력하지 않는 문제 발생
def qsort(arr):
    if len(arr) < 2:
        return arr
    pivot = arr[0]
    low = [i for i in arr if i < pivot]
    high = [i for i in arr if i > pivot]
    return qsort(low) + [pivot] + qsort(high)

my_list = [24, 222, 2, 2, 2, 44, 2, 16, 32, 31, 25]
print("정렬 전:")
print(my_list)
print()
print("정렬 후:")
print(qsort(my_list))

정렬 전:
[24, 222, 2, 2, 2, 44, 2, 16, 32, 31, 25]

정렬 후:
[2, 16, 24, 25, 31, 32, 44, 222]

In [10]:
# 풀이2
def qsort(arr):
    if len(arr) < 2:
        return arr
    pivot = arr[0]
    low = []
    high = []
    for i in range(1, len(arr)):
        if arr[i] < pivot:
            low.append(arr[i])
        else:
            high.append(arr[i])
    return qsort(low) + [pivot] + qsort(high)

my_list = [24, 222, 2, 2, 2, 44, 2, 16, 32, 31, 25]
print("정렬 전:")
print(my_list)
print()
print("정렬 후:")
print(qsort(my_list))

정렬 전:
[24, 222, 2, 2, 2, 44, 2, 16, 32, 31, 25]

정렬 후:
[2, 2, 2, 2, 16, 24, 25, 31, 32, 44, 222]

In [11]:
# 풀이3
def qsort(arr):
    if len(arr) < 2:
        return arr
    pivot = arr[0]
    low = []
    high = []
    for value in arr[1:]:
        if value < pivot:
            low.append(value)
        else:
            high.append(value)
    return qsort(low) + [pivot] + qsort(high)

my_list = [24, 222, 2, 2, 2, 44, 2, 16, 32, 31, 25]
print("정렬 전: ")
print(my_list)
print()
print("정렬 후: ")
print(qsort(my_list))

정렬 전:
[24, 222, 2, 2, 2, 44, 2, 16, 32, 31, 25]

정렬 후:
[2, 2, 2, 2, 16, 24, 25, 31, 32, 44, 222]